apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization
  template:
    metadata:
      labels:
        app: authorization
    spec:
      dnsConfig:
        nameservers: {{ toYaml .Values.dns | nindent 8 }}
      containers:
        - name: authorization
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: {{ toYaml .Values.command | nindent 10 }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: NODE_EXTRA_CA_CERTS
              value: "{{ .Values.env.NODE_EXTRA_CA_CERTS }}"
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
