apiVersion: v1
kind: Service
metadata:
  name: authorization
spec:
  type: {{ .Values.service.type }}
  selector:
    app: authorization
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
